---
---

<link rel="stylesheet" href="styles.css" type="text/css">


### Editorial work and peer review

I'm an editorial board member for 

- <a href="https://www.nature.com/srep/" target="_blank">Scientific Reports</a href> (Psychology)
- <a href="https://www.tandfonline.com/journals/rigs20My" target="_blank">International Gambling Studies</a href>

My previous editorial responsibilities include

- Research topic editor for <a href="https://www.frontiersin.org/research-topics/9288/high-performance-cognition-information-processing-in-complex-skills-expert-performance-and-flow" target="_blank">Frontiers in Psychology</a href>
- Associate editor for <a href="https://jeps.efpsa.org/" target="_blank">Journal of European Psychology Students</a href>
- Ad hoc academic editor for <a href="https://journals.sagepub.com/home/sgo" target="_blank">Sage OPEN</a href>


I've written about 50 peer reviews, excluding reviews of revised manuscripts, for

- Journal of Gambling Studies
- Frontiers in Psychology
- International Gambling Studies
- Legal and Criminological Psychology
- Cognitive Science
- International Journal of Human-Computer Studies
- Neuropsychiatric Disease and Treatment
- Gerontology
- IEEE Access
- Learning and Individual Differences
- Basic and Applied Social Psychology
- Nordic Conference on Human-Computer Interaction
- Workshop on Socio-Technical Aspects in Security and Trust
- Routledge Books (Applied Psychology)
- IGI Global
- Annual Meeting of the Cognitive Science Society
- SAGE Open
- Journal of Behavioral Addictions