---
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 4
---

<link rel="stylesheet" href="styles.css" type="text/css">

<font size=5>Peer-reviewed publications</font>

I've (co)authored 62 scientific papers, 52 of which have been peer-reviewed (19 as first author, 11 as second author, and 9 as last author). My papers focus on 1) gambling, games, and behavioral addictions, 2) social psychology and moral psychology of robotics, 3) emotions, decision-making, and psychophysiological correlates of cognition, and 4) psychology of deception.

My papers are listed below topic-wise, though some papers fit multiple topics. If you want a paper you can't access, I'll be happy to <a href="contact.html">email</a href> you a copy.

<br>


#### Gambling, games, and behavioral addictions


- <a href="https://link.springer.com/article/10.1007/s11469-024-01290-4"> Männikkö, N., <b>Palomäki, J.</b>, Parikka, S., Määttänen, I., & Castrén, S. (2024). Establishing Academic Burnout’s Relationship with Problematic Internet Use and Specific Health-Risk Behaviours: A Cross-sectional Study of Finnish Higher Education Students. <i>International Journal of Mental Health and Addiction, 1-20.</i> </a href>

- <a href="https://doi.org/10.1016/j.comppsych.2023.152414" target="_blank"> Korvuo, T., <b>Palomäki, J.</b>, & Castrén, S. (2023). Dissociative experiences reduce online problem gambling treatment effectiveness. <i>Comprehensive Psychiatry</i>, 127, 152414. </a href>

- <a href="https://akjournals.com/view/journals/2006/12/3/article-p711.xml" target="_blank"><b>Palomäki, J.</b>, Turner, N., Macey, J., & Castrén, S. (in press). Increased volatility in video poker results in more winning players but shorter winning streaks – evidence from simulations. <i> Journal of Behavioral Addictions, 12</i>(3), 711-720. </a href>

- Arstila, V., Uusitalo, S., & <b> Palomäki, J. </b> (in press). Miksi pelaamme rahapelejä? In S. Uusitalo & V. Arstila (Eds.), <i>Ongelmallinen rahapelaaminen: näkökulmia rahapelaamisen varjoihin ja tutkimuksen katvealueisiin.</i> Turku: Eetos.

- <b>Palomäki, J.</b>, Salmela, M., & Laakasuo, M. (in press). Emootiot ja niiden säätely rahapelaamisessa. In S. Uusitalo & V. Arstila (Eds.), <i>Ongelmallinen rahapelaaminen: näkökulmia rahapelaamisen varjoihin ja tutkimuksen katvealueisiin.</i> Turku: Eetos.

- <a href="https://www.researchgate.net/profile/Jussi-Palomaeki/publication/362620086_Predicting_online_problem_gambling_treatment_discontinuation_New_evidence_from_cross-validated_models/links/62f4b35bc6f6732999c1cc4c/Predicting-Online-Problem-Gambling-Treatment-Discontinuation-New-Evidence-From-Cross-Validated-Models.pdf" target="_blank"><b>Palomäki, J.</b>, Lind, K., Heiskanen, M., & Castrén, S. (2022). Predicting online problem gambling treatment discontinuation: New evidence from cross-validated models. <i>Psychology of Addictive Behaviors, 37</i>(3), 519-532.</a href>

- <a href="https://www.nature.com/articles/s41598-022-24715-3" target="_blank">Laakasuo, M., <b>Palomäki, J.</b>, Abuhamdeh, S., Lappi, O., & Cowley, B. U. (2022). Psychometric analysis of the flow short scale translated to Finnish. <i>Scientific Reports, 12</i>(1), 1-11.</a href>

- <a href="https://www.sciencedirect.com/science/article/pii/S0747563221002144" target="_blank"><b>Palomäki, J.</b>, Tammi, T., Lehtonen, N., Seittenranta, N., Laakasuo, M., Abuhamdeh, S., Lappi, O., & Cowley, B. U. (2021). The link between flow and performance is moderated by task experience. <i>Computers in Human Behavior</i>, 124, 106891.</a href>

- <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/jopy.12637" target="_blank"><b>Palomäki, J.</b>, Laakasuo, M., Castrén, S., Saastamoinen, J., Kainulainen, T., & Suhonen, N. (2021). Online betting intensity is linked with Extraversion and Conscientiousness. <i>Journal of Personality, 89</i>(5), 1081-1094.</a href>

- <a href="https://akjournals.com/view/journals/2006/11/1/article-p75.xml" target="_blank"><b>Palomäki, J.</b>, Heiskanen, M., & Castrén, S. (2022). Online 8-week cognitive therapy for problem gamblers: The moderating effects of depression symptoms and perceived financial control. <i>Journal of Behavioral Addictions, 11</i>(1), 75-87.</a href>

- <a href="https://www.journalofexpertise.org/articles/volume3_issue2/JoE_3_2_Palomaki_etal_earlyview.html" target="_blank"><b>Palomäki, J.</b>, Laakasuo, M., Cowley, B. U., & Lappi, O. (2020). Poker as a Domain of Expertise. <i>Journal of Expertise, 3</i>(2).</a href>

- <a href="https://www.frontiersin.org/articles/10.3389/fpsyg.2019.01126/full" target="_blank">Cowley, B. U., <b>Palomäki, J.</b>, Tammi, T., Frantsi, R., Inkilä, V. P., Lehtonen, N., Pölönen, P., Vepsäläinen, J., &amp; Lappi, O. (2019). Flow experiences during visuomotor skill acquisition reflect deviation from a power-law learning curve, but not overall level of skill. <i>Frontiers in Psychology, 10</i>, 1126. (BC, JP, TT Equal contributors)</a href>

- <a href="https://link.springer.com/article/10.1007/s10899-018-9795-6" target="_blank">Oikonomidis, A., <b>Palomäki, J.</b>, &amp; Laakasuo, M. (2019). Experience and passion in poker: Are there well-being implications? <i>Journal of Gambling Studies, 35</i>(2), 731–742.</a href>

- <a href="https://www.sciencedirect.com/science/article/pii/S1071581918303665?casa_token=IbW1KRZM18IAAAAA:KxZocMXN4FMt55zkADZszxDe7gk3CFmQuX5zjzLGa60eWiGC--XK5HRAu2ufkS_w9b6swaGZug" target="_blank">Kosunen, I., <b>Palomäki, J.</b>, Laakasuo, M., Kuikkaniemi, K., Ravaja, N., & Jacucci, G. (2018). Heart-rate sonification biofeedback for poker. <i>International Journal of Human-Computer Studies</i>, 120, 14-21.</a href>

- <a href="https://dl.acm.org/doi/pdf/10.1145/2911996.2912019?casa_token=iSqkOlL-EBoAAAAA:2WCabqO_-Q5OyGp_6PTNNkhhAZ6IqQVLpOI9hd9vflmYi75jZF_apDikmY2aKqP1aNqiZDY52agD" target="_blank">Wei, X., <b>Palomäki, J.</b>, Yan, J., &amp; Robinson, P. (2016). The science and detection of tilting. In <i>Proceedings of the 2016 ACM on International Conference on Multimedia Retrieval</i> (pp. 79-86). (XW, JP Equal contributors)</a href>

- <a href="https://journal.gamblingstudies.org/index.php/jgcg/article/view/83" target="_blank">Laakasuo, M., <b>Palomäki, J.</b>, &amp; Salmela, M. (2015). Poker players with experience and skill are not “ill” – Exposing a discrepancy in measures of problem gambling. <i>Journal of Gambling and Commercial Gaming Research</i>, 1. Selected for “best paper” -award at the Second Asia Pacific Conference on Gambling &amp; Commercial Gaming Research (APCG2013)</a href>

- <a href="https://www.researchgate.net/profile/Jussi-Palomaeki/publication/301358233_Pokerin_psykologiaa/links/571532ed08ae8ab56695a77d/Pokerin-psykologiaa.pdf" target="_blank">Laakasuo, M., <b>Palomäki, J.</b>, Lappi, O. (2015). Pokerin psykologiaa (The psychology of poker). <i>Psykologia, 50</i>(3), 180–193. (ML, JP Equal contributors)</a href>

- <a href="https://www.liebertpub.com/doi/pdf/10.1089/cyber.2014.0147?casa_token=sx1_zXMxEqUAAAAA%3AvD_pnM5d-rtkaSF9BROe_ys3yIJfGin7c7If4sCkGm5ecHtXInKFS5d17ZkPgrBJa6WmjBq-hg" target="_blank">Laakasuo, M., <b>Palomäki, J.</b>, &amp; Salmela, M. (2014). Experienced poker players are emotionally stable. <i>Cyberpsychology, Behavior, and Social Networking, 17</i>(10), 668–671.</a href>

- <a href="https://link.springer.com/article/10.1007/s10899-014-9454-5" target="_blank">Laakasuo, M., <b>Palomäki, J.</b>, &amp; Salmela, M. (2014). Emotional and social factors influence poker decision making accuracy. <i>Journal of Gambling Studies, 31</i>(3), 933–947.</a href>

- <a href="https://link.springer.com/article/10.1007/s10899-012-9339-4" target="_blank"> <b>Palomäki, J.</b>, Laakasuo, M., &amp; Salmela, M. (2014). Losing more by losing it: Poker experience, sensitivity to losses and tilting severity. <i>Journal of Gambling Studies, 30</i>(1), 187–200.</a href>

- <a href="https://psycnet.apa.org/record/2013-16456-004" target="_blank"><b>Palomäki, J.</b>, Kosunen, I., Kuikkaniemi, K., Yamabe, T., &amp; Ravaja, N. (2013). Anticipatory electrodermal activity and decision making in a computer poker-game. <i>Journal of Neuroscience, Psychology, and Economics, 6</i>(1), 55–70. Selected to be among the best 10 papers published in the journal at the 10 th Anniversary NeuroPsychoEconomics Conference.</a href>

- <a href="https://link.springer.com/article/10.1007/s10899-012-9311-3" target="_blank"><b>Palomäki, J.</b>, Laakasuo. M., &amp; Salmela, M. (2013). ”Don&#39;t worry, it&#39;s just poker!” - Experience, self-rumination and self-reflection as determinants of decision-making in on-line poker. <i>Journal of Gambling Studies, 29</i>(3), 491–505.</a href>

- <a href="https://www.tandfonline.com/doi/abs/10.1080/14459795.2013.780631?casa_token=Gn3ZKVCWHqcAAAAA:82NEK2SXJcm-nTXfpemxIUPyrmnQxHNGt6dKYfCMlV6VBjFteBkp_vn0CUnVdiu6lBsZAgMMF6rv" target="_blank"><b>Palomäki, J.</b>, Laakasuo, M., & Salmela, M. (2013). ‘This is just so unfair!’: A qualitative analysis of loss-induced emotions and tilting in on-line poker. <i>International Gambling Studies, 13</i>(2), 255-270.</a href>


<br>

#### Social psychology and moral psychology of robotics

- Raitasalo, K., Karjalainen, K., Ollila, H., & <b>Palomäki, J.</b> (in press). Suomalaisten korkeakouluopiskelijoiden päihteiden käyttö vuonna 2021: KOTT-tutkimuksen tuloksia. <i>Sosiaalilääketieteellinen aikakauslehti.</i>

- Laakasuo, M., Sundvall, J., Francis, K. B., Drosinou, M-A., Hannikainen, I., Kunnari, A. J. O., & <b>Palomäki, J.</b> (in press). Would you exchange your soul for immortality? Existential meaning and afterlife beliefs predict mind upload approval. <i>Frontiers in Psychology.</i>

- <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/jasp.13010" target="_blank">Drosinou, M., <b>Palomäki, J.</b>, Kunnari, A., Koverola, M., Jokela, M. & Laakasuo, M. (in press). Modelling levels of eco-conscious awareness. <i>Journal Applied Social Psychology.</i></a href>

- <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/ejsp.2936" target="_blank">Sundvall, J., Drosinou, M., Hannikainen, I., Elovaara, K., Halonen, J., Herzon, V., Kopecký, R., Jirout Košová, M., Koverola, M., Kunnari, A., Perander, S., Saikkonen, T., <b>Palomäki, J.</b>, & Laakasuo, M. (2023). Innocence over utilitarianism - Heightened Moral Standards for Robots in Rescue Dilemmas. <i>European Journal of Social Psychology, 53</i>(4), 779-804.</a href>

- <a href="https://doi.org/10.31234/osf.io/a3562" target="_blank">Azevedo, F., Pavlović, T., + 260 authors including <b>Palomäki, J.</b> (in press.). Social and moral psychology of COVID-19 across 69 countries. <i>Scientific Data.</i></a href>  

- <a href="https://academic.oup.com/pnasnexus/article/1/3/pgac093/6631580" target="_blank">Pavlović, T., Azevedo, F., + 260 authors including <b>Palomäki, J.</b> (2022). Predicting attitudinal and behavioral responses to COVID-19 pandemic using machine learning. <i>PNAS Nexus, 1</i>(3), pgac093.</a href>

- <a href="https://www.nature.com/articles/s41467-021-27668-9" target="_blank">Van Bavel, J.J., Cichocka, A., + 260 authors including <b>Palomäki, J.</b> (2022). National identity predicts public health support during a global pandemic. <i>Nature Communications, 13</i>(1), 1-14.</a href>

- <a href="https://www.sciencedirect.com/science/article/pii/S0022103122000701" target="_blank">Koverola, M., Kunnari, A., Drosinou, M., <b>Palomäki, J.</b>, Hannikainen, I. R., Košová, M. J., Kopecký, R., Sundvall, J., & Laakasuo, M. (2022). Treatments approved, boosts eschewed: Moral limits of neurotechnological enhancement. <i>Journal of Experimental Social Psychology</i>, 102, 104351.</a href>

- <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/ejsp.2890" target="_blank">Laakasuo, M., <b>Palomäki, J.</b>, Kunnari, A., Rauhala, S., Drosinou, M., Halonen, J., Lehtonen, N., Koverola, M., Repo, M., Sundvall, J., Visala, A., & Francis, K. B. (2022). Moral psychology of nursing robots: Exploring the role of robots in dilemmas of patient autonomy. <i>European Journal of Social Psychology</i>. Advance online publication.</a href>

- Laakasuo, M., Sundvall, J., Berg, A., Drosinou, M., Herzon, V., Kunnari, A., Koverola, M., Repo, M., Saikkonen, T., & <b>Palomäki, J.</b> (2021). Moral psychology and artificial agents (Part 1): Ontologically categorizing bio-cultural humans. In S. Thompson (Ed.), <i>Machine Law, Ethics and Morality in the Age of Artificial Intelligence.</i> New York: IGI Global.

- <a href="https://helda.helsinki.fi/bitstream/handle/10138/337163/MoralPsychologyAndArtificialAgents_Part2.pdf?sequence=1" target="_blank">Laakasuo, M., Sundvall, J., Berg, A., Drosinou, M., Herzon, V., Kunnari, A., Koverola, M., Repo, M., Saikkonen, T., & <b>Palomäki, J.</b> (2021). Moral psychology and artificial agents (Part 2): The transhuman connection. In S. Thompson (Ed.), <i>Machine Law, Ethics and Morality in the Age of Artificial Intelligence.</i> New York: IGI Global.</a href>

- <a href="https://link.springer.com/article/10.1007/s12369-020-00738-6" target="_blank">Laakasuo, M., Köbis, N., & <b>Palomäki, J.</b> (2021) A robot’s appearance moderates how its decisions are judged. <i>International Journal of Social Robotics, 13</i>(7), 1679–1688.</a href>

- <a href="https://link.springer.com/article/10.1007/s43681-021-00060-5" target="_blank">Laakasuo, M., Herzon, V., Perander, S., Drosinou, M., Sundvall, J., <b>Palomäki, J.</b>, & Visala, A. (2021). Socio-cognitive biases in folk AI ethics and risk discourse. <i>AI and Ethics, 1</i>(4), 593–610.</a href>

- <a href="https://helda.helsinki.fi/bitstream/handle/10138/324246/AJATUS77_07_artikkeli_Laakasuo_Visala_Palom_ki.pdf?sequence=1" target="_blank">Laakasuo, M., Visala, A., &amp; <b>Palomäki, J.</b> (2020). Kuinka ihmismieli vääristää keskustelua tekoälyn riskeistä ja etiikasta – Kognitiotieteellisiä näkökulmia keskusteluun. <i>Ajatus, 77</i>(1), 131–168.</a href>

- <a href="https://www.degruyter.com/document/doi/10.1515/pjbr-2020-0012/html" target="_blank">Koverola, M., Drosinou, M., <b>Palomäki, J.</b>, Halonen, J., Kunnari, A., Repo, M., Lehtonen, N., &amp; Laakasuo, M. (2020). Moral psychology of sex robots: An experimental study – how pathogen disgust is associated with interhuman sex but not interandroid sex. <i>Paladyn, Journal of Behavioral Robotics, 11</i>(1), 233–249.

- <a href="https://www.sciencedirect.com/science/article/pii/S2405844018339586" target="_blank"><b>Palomäki, J.</b>, Kunnari, A., Drosinou, M., Koverola, M., Lehtonen, N., Halonen, J., Repo, M., &amp; Laakasuo, M. (2018). Evaluating the replicability of the uncanny valley effect. <i>Heliyon, 4</i>(11), e00939.</a href>

- <a href="https://www.nature.com/articles/s41599-018-0124-6" target="_blank">Laakasuo, M., Drosinou, M., Koverola, M., Kunnari, A., Halonen, J., Lehtonen, N., & <b>Palomäki, J.</b> (2018). What makes people approve or condemn mind upload technology? Untangling the effects of sexual disgust, purity and science fiction familiarity. <i>Palgrave Communications, 4</i>(1), 1-14.</a href>

- <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/ijop.12416?casa_token=n5w2_HxbED0AAAAA%3AKpvF9VP08EyVBnzMaMaq2erF5a1HiViOK-f1obaVoy9eKHfPpk_mLhjIBLxI2he7TGwGl1inxb_LIQ" target="_blank">Laakasuo, M., Köbis, N., <b>Palomäki, J.</b>, &amp; Jokela, M. (2018). Money for microbes – Pathogen avoidance and out-group helping behavior. <i>International Journal of Psychology, 53</i>(1), 1–10.</a href>


<br>


#### Emotions, decision-making, and psychophysiological correlates of cognition

- Saarinen, V.A., & <b>Palomäki, J.</b> (2021). Psykojuridinen näkökulma tuomarin päätöksentekoon, erityisesti rangaistuksen määräämiseen. <i>Lakimies, 119</i>(6), 993–1014.

- <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8741145/" target="_blank">Cowley, B. U., Juurmaa, K., & <b>Palomäki, J.</b> (2022). Reduced power in fronto-parietal theta EEG linked to impaired attention-sampling in adult ADHD. <i>Eneuro, 9</i>(1).</a href>

- <a href="https://helda.helsinki.fi/bitstream/handle/10138/337450/965_Article_Text_8261_2_10_20211202.pdf?sequence=1" target="_blank">Määttä, O., McIntyre, N., <b>Palomäki, J.</b>, Hannula, M. S., Scheinin, P., & Ihantola, P. (2021). Students in sight: Using mobile eye-tracking to investigate mathematics teachers’ gaze behaviour during task instruction-giving. <i>Frontline Learning Research, 9</i>(4), 92-115.</a href>

- <a href="https://www.sciencedirect.com/science/article/pii/S2405844021003480" target="_blank">Määttänen, I., Henttonen, P., Väliaho, J., <b>Palomäki, J.</b>, Thibault, M., Kallio, J., Mäntyjärvi, J., Harviainen, T., & Jokela, M. (2021). Positive affect state is a good predictor of movement and stress: combining data from ESM/EMA, mobile HRV measurements and trait questionnaires. <i>Heliyon, 7</i>(2), e06243.</a href>

- <a href="https://www.tandfonline.com/doi/full/10.1080/23311908.2019.1575654" target="_blank">Määttänen, I., Martikainen, J., Henttonen, P., Väliaho, M., Thibault, M., &amp; <b>Palomäki, J.</b> (2019). Understanding depressive symptoms through psychological traits and physiological stress reactivity. <i>Cogent Psychology</i>, 1575654.</a href>

- <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/ejsp.2890" target="_blank"><b>Palomäki, J.</b>, Kivikangas, M., Alafuzoff, A., Hakala, T., & Krause, C. M. (2012). Brain oscillatory 4–35 Hz EEG responses during an n-back task with complex visual stimuli. <i>Neuroscience Letters, 516</i>(1), 141-145.</a href>

- <a href="https://www.researchgate.net/profile/Michael-Laakasuo/publication/289635550_Ihmisen_emootiot_paatoksenteko_ja_rationaalisuus/links/62b01422a920e8693e036970/Ihmisen-emootiot-paeaetoeksenteko-ja-rationaalisuus.pdf?_sg%5B0%5D=started_experiment_milestone&origin=journalDetail" target="_blank"><b>Palomäki, J.</b>, Laakasuo, M., &amp; Lappi, O. (2012). Ihmisen emootiot, päätöksenteko ja rationaalisuus. <i>Ajatus</i>, 69, 91–120.</a href>

<br>



#### Psychology of deception

- <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0157838" target="_blank"><b>Palomäki, J.</b>, Yan, J., Modic, D., & Laakasuo, M. (2016). "To bluff like a man or fold like a girl?" –Gender biased deceptive behavior in online poker. <i>PloS ONE, 11</i>(7), e0157838.</a href>

- <a href="https://www.sciencedirect.com/science/article/pii/S0191886916302434" target="_blank"><b>Palomäki, J.</b>, J., Yan, J., & Laakasuo, M. (2016). Machiavelli as a poker mate —A naturalistic behavioural study on strategic deception. <i>Personality and Individual Differences</i>, 98, 266-271.</a href>

- <a href="https://www.tandfonline.com/doi/full/10.1080/23311908.2018.1469579" target="_blank">Modic, D., <b>Palomäki, J.</b>, Drosinou, M., & Laakasuo, M. (2018). The dark triad and willingness to commit insurance fraud. <i>Cogent Psychology, 5</i>(1), 1469579.</a href>

- <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0194119" target="_blank">Modic, D., Anderson, R., & <b>Palomäki, J.</b> (2018). We will make you like our research: The development of a susceptibility-to-persuasion scale. <i>PloS ONE, 13</i>(3), e0194119.</a href>
